new/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                                        document_root=settings.MEDIA_ROOT)

new/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.HomePage.as_view(),name='home'),
    path('student/register', views.StudentCreate.as_view(), name='student_register'),
    path('hire/teacher', views.TeacherHire.as_view(), name='teacher_hiring'),
    path('add/course', views.AddCourseView.as_view(), name='add_course'),
    path('course/<int:pk>', views.CourseDetail.as_view(), name='course_detail'),
    path('payment/course_list/', views.PaymentCourseList.as_view(), name='payment_course_list'),
    path('payment/course_list/<int:pk>/', views.payment_view, name='payment')
]

new/courses/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.template.defaultfilters import slugify


# class Days(models.TextChoices):
#     monday = "Monday", _("Monday")
#     tuesday = "Tuesday", _("Tuesday")
#     wednesday = "Wednesday", _("Wednesday")
#     thursday = "Thursday ", _("Thursday")
#     friday = "Friday", _("Friday")
#     saturday = "Saturday", _("Saturday")
#     sunday = "Sunday", _("Sunday")

class Days(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)


    def __str__(self):
        return self.name
    

class Course(models.Model):
#     DEMO_CHOICES =( 
#     ("Du", "Dushanba"), 
#     ("se", "Seshanba"), 
#     ("chor", "Chorshanba"), 
#     ("pa", "Payshanba"), 
#     ("ju", "Juma"), 
#     ("shan", "Shanba"), 
#     ("yak", "Yakshanba"), 
# ) 
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    created = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    fixed_price = models.PositiveIntegerField(default=0)
    days = models.ManyToManyField(Days)
    time = models.CharField(max_length=40)


    def __str__(self):
        return self.title


class Teacher(models.Model):
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    courses = models.ManyToManyField(Course, related_name='teacher')


    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    courses = models.ManyToManyField(Course, related_name='students')
    
    
    def __str__(self):
        return self.name


class Attendance(models.Model):
    DEMO_CHOICES =( 
    ("true", "Keldi"), 
    ("false", "Kelmadi"),
    ) 
    user = models.ForeignKey(Student, on_delete=models.CASCADE,related_name='attendence_student',unique_for_date='date')
    subject = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField()
    attandence = models.CharField(max_length=40,choices=DEMO_CHOICES)

    def __str__(self):
        return f"{self.user.name} - {self.date}"

class Payment(models.Model):
    user = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    date = models.DateTimeField()
    active = models.BooleanField(default=False)


    def __str__(self):
        return self.user.name
    

# Signals
# @receiver(post_save, sender=Problem)
# def attendence_created(sender,instance, created,  **kwargs):
#     if created:
#         student = instance
#         print(student.courses.all())
#         problem = Attendance.objects.create(
#             user = student,
#             # subject = student.courses,
#             date =  datetime.now(),
#             attandence = 'true'
#         )
# @receiver(post_delete, sender=Problem)
# def probleme_deleted(sender, instance,**kwargs):
#     print('Post deleted')
#     print('Post was', instance.title)

# post_save.connect(attendence_created,sender=Student)
# post_delete.connect(probleme_deleted,sender=Problem)

new/courses/forms.py
from django import forms
from .models import Course, Student, Teacher, Attendance, Payment



class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        widgets = {
            'courses': forms.SelectMultiple(attrs={'multiple':'','class':'select'})
        }


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        widgets = {
            'courses': forms.SelectMultiple(attrs={'multiple':'','class':'select'})
        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        exclude = ['slug']
        widgets = {
            'title':forms.TextInput(),
            'description':forms.Textarea(),
            'days': forms.SelectMultiple(attrs={'multiple':'','class':'select'})
        }      


class AttendanceForm(forms.ModelForm):

    class Meta:
        model = Attendance
        fields = '__all__'
        exclude = ['subject']
        widgets = {
            'date': forms.DateInput(
                attrs={'type':'date'})
        }      


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'
        widgets = {
            'user' : forms.Select(attrs={'class':'bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700'}),
            'course': forms.Select(attrs={'class':'bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700'}),
            'date': forms.DateInput(
                attrs={'type':'date','class':'bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700'}),
            'active': forms.CheckboxInput()
        }      

new/courses/views.py
import datetime
from typing import Any
from django.db import models
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView , FormMixin
from django.utils.text import slugify
from .forms import CourseForm, StudentForm, TeacherForm, AttendanceForm, PaymentForm
from django.db.models.functions import Extract

# from django.dispatch import receiver
# from django.db.models.signals import post_save, post_delete
# from django.template.defaultfilters import slugify


   
# Models
from .models import Student, Teacher, Course, Attendance, Payment

class HomePage(ListView):
    model = Course
    template_name = 'index.html'



class StudentCreate(CreateView):
    model = Student
    form_class = StudentForm
    success_url =  reverse_lazy('courses:home')


class TeacherHire(CreateView):
    model = Teacher
    form_class = TeacherForm
    template_name = 'courses/student_form.html'
   


class AddCourseView(CreateView):
    model = Course
    form_class = CourseForm
    success_url = reverse_lazy('courses:home')

    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.slug = slugify(self.object.title)
        return super().form_valid(form)

current_date = datetime.datetime.now()


class CourseDetail(FormMixin,DetailView):
    model = Course
    form_class = AttendanceForm
    
    def get_success_url(self):
        return reverse('courses:course_detail', kwargs={'pk': self.object.id})

    def form_valid(self, form: Any):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        object = self.get_object()
        student = self.get_object().students.all()
        payment = self.get_object().payment_set.all()
        attandence = self.object.attendance_set.filter(date=current_date)
        print(student)
        return {
            'object':object,
            'student':student,
            'current_date':current_date,
            'form':AttendanceForm(),
            'attandence':attandence,
            'payment':payment
        }
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        

    def form_valid(self, form):
        form.save()
        return super(CourseDetail, self).form_valid(form)

class PaymentCourseList(ListView):
    model = Course

def payment_view(request,pk):
    template_name = 'courses/course_form.html'
    students = Student.objects.filter(courses=Course.objects.get(id=pk))
   
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            student = form.cleaned_data['user']
            course = form.cleaned_data['course']
            payment_month = student.payment_set.get(date__month=current_date.now().month)
            print(payment_month)
            # payment_month = student.payment_set.annotate(month_stamp=Extract('date', 'month')).values_list('month_stamp', flat=True)
            # payment = student.payment_set.get(date__month=current_date.month)
            if payment_month:
                if payment_month.course == course:
                    return HttpResponse('<h1>This student has already made a payment for this month</h1>')
                else:
                    form.save()
            else:
                form.save()
        else:
            return HttpResponse('<h1>Fill all the fields</h1>')
    else:
        form = PaymentForm()
    context = {
        'form' : form,
        'student' : students
    }
    return render(request, template_name,context)

new/templates/courses/attandence.html
{% extends 'base.html' %}
{% block title %}Attandence{% endblock title%}
{% block content %}
<div class="container">
  
<div class="relative overflow-x-auto">
  <form action="" method="POST">
    {% csrf_token %}
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Student
                </th>
                <th scope="col" class="px-6 py-3">
                  Attendence
                </th>
                <th>
                  Calendar
                </th>
                <th scope="col" class="px-6 py-3">
                    payment
                </th>
            </tr>
        </thead>
        <tbody>
          
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <select name="user" id="id_user">
                  <option value selected >-----</option>
                  {% for i in student  %}
                    <option value="{{ i.id }}">{{ i.name }}</option>
                  {% endfor %}
                </select>
            </th>
            <td class="px-6 py-4">
                {{form.date}}
            </td>
            <td class="px-6 py-4">
                {{ form.attandence }}
            </td>
          </tr>
        </tbody>
    </table>
    <button type="submit" class="py-2 px-4 text-white bg-blue-700 rounded-lg">save</button>
  </form>
</div>

</div>
<script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>0
{% endblock content %}

new/templates/courses/course_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.title }}-{{ object.time }}{% endblock title %}
{% block content %}
<div class="container py-4">
    <style>
        table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
    </style>
    <h1 class="mb-4 font-bold text-3xl">Course</h1>
    <div class="card shadow-lg rounded-lg w-full p-4">
        <div class="flex justify-between items-center ">
            <div class="title text-3xl font-bold">{{ object.title }}</div>
            <div class="text-gray-600 text-2xl">{{ object.time }}</div>
        </div>
        <div class="body mt-4">
            {{ object.description }}
        </div>
        <div class="flex gap-x-4">
            {% for days in object.days.all %}
                <p class="py-2 px-4 bg-yellow-400 rounded-lg text-white mt-2">{{ days }}</p>
            {% endfor %}
        </div>
        <div class="mt-4 py-2 px-4 rounded-lg bg-gray-700 text-white">
          Helds 3 days in a week
      </div>
        <div class="py-2 px-3 text-white bg-blue-700 rounded-lg mt-2">
            there are  {{ object.students.count }} of students
        </div>
    </div>
    <div class="flex justify-between items-center">
      <h1 class="mt-4 font-bold text-3xl mb-2">Attandance</h1>
    <p>{{ current_date.day }}.{{ current_date.month}}.{{ current_date.year}}</p>
    </div>
    <div class="relative overflow-x-auto">
      <form action="{% url 'courses:course_detail' object.id %}" method="POST">
        {% csrf_token %}
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Student
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Attendence
                    </th>
                    <th>
                      Calendar
                    </th>
                </tr>
            </thead>
            <tbody>
              
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <select name="user" id="id_user">
                      <option value selected >-----</option>
                      {% for i in student  %}
                        <option value="{{ i.id }}">{{ i.name }}</option>
                      {% endfor %}
                    </select>
                </th>
                <td class="px-6 py-4">
                    {{form.date}}
                </td>
                <td class="px-6 py-4">
                    {{ form.attandence }}
                </td>
              </tr>
             {% for i in attandence %} 
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                   {{ i.user.name }}
                </th>
                <td class="px-6 py-4">
                    {{ i.attendence_student.attandence }}
                </td>
                <td class="px-6 py-4">
                    {{ i.payment_set.last }}
                </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="py-2 px-8 text-white bg-blue-700 rounded-lg mt-2">save</button>
      </form>
    </div>
    <div>
      <h1 class="font-bold mt-10 text-3xl mb-4">Payments</h1>
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Students
                </th>
                <th scope="col" class="px-6 py-3">
                  payment status
                </th>
            </tr>
        </thead>
        <tbody>
          {% for i in payment %}
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                {{ i.user.name }} {{ i.user.surname }}
            </th>
            <td class="px-6 py-4">
                {{ i.active }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock content %}

new/templates/courses/course_form.html
{% extends 'base.html' %}
{% block title %}Add Course{% endblock title %}
{% block content %}
{% load tailwind_filters %}
<div class="container">
    <style>
        .wrap_form{
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .form{
            width: 500px;
            height: 100vh;
            padding: 2% 2%;
        }
    </style>
    <div class="wrap_form py-10">
        <div class="form shadow-lg rounded-lg mt-10">
            <form method="POST">
                {% csrf_token %}
                <p>
                    <select name="user" id="id_user" class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700">
                        <option value selected >-----</option>
                        {% for i in student  %}
                          <option value="{{ i.id }}">{{ i.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p class="mt-10">{{ form.course }}</p>
                <p class="mt-10">{{ form.date }}</p>
                <p class="mt-10 mb-4">{{ form.active }}</p>
                <button type="submit" class="py-2 px-4 rounded-lg bg-blue-600 text-white text-sm w-full">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

new/templates/courses/course_list.html
{% extends 'base.html' %}
{% block title %}Courses Lists{% endblock title %}
{% block content %}
<div class="container">
    <style>
        .grid{
            width: 100%;
            padding: 5% 0;
        }
    </style>
    <div class="grid grid-cols-1 grid-rows-1 gap-x-4 lg:grid-cols-2 md:grid-cols-2 sm:grid-cols-1 gap-y-4 ">
        {% for course in object_list %}
            <div class="card shadow-lg p-4 rounded-lg mt-10">
                <a href="{% url 'courses:payment' course.id %}" class="title font-bold text-2xl">{{ course.title }}</a>
                <div class="body mt-8">{{ course.description }}</div>
                <div class="mt-5">
                    <div>this course starts at {{ course.time }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

new/templates/courses/student_form.html
{% extends 'base.html' %}
{% block title %}Student Registration{% endblock title %}
{% block content %}
{% load tailwind_filters %}
<div class="container">
    <style>
        .wrap_form{
            width: 100%;
            height:65vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .form{
            width: 500px;
            padding: 4% 3%;
            border-radius: 10px;
            margin: 0 auto;
        }
    </style>
    <div class="wrap_form">
        <div class="form shadow-lg">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="py-2 px-4 rounded-lg bg-blue-600 text-white text-sm">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}