devforum-1.0/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls', namespace='forum')),
    path('users/', include('users.urls', namespace='users')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name = 'users/reset_password.html'), 
        name ='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'), 
        name ='password_reset_done'),
    path('reset/password/<str:uidb64>/<str:token>', auth_views.PasswordResetConfirmView.as_view(
         template_name = 'users/password_reset_confirm.html'),
         name ='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'users/password_reset_complete.html'),
        name ='password_reset_complete'),
    path("__debug__/", include("debug_toolbar.urls")),
]

devforum-1.0/forum/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'forum'
urlpatterns = [
    path('', cache_page(60*15)(views.HomePage.as_view()), name='home'),
    path('detail/<pk>', views.ProblemDetail.as_view(),name='problem_detail'),
    path('problem_add/', views.AddProblem.as_view(), name='add'),
]

devforum-1.0/users/urls.py
from django.urls import path, re_path

from django.contrib.auth.views import ( 
    LoginView,
    LogoutView,
    )   
from . import views

app_name = 'users'
urlpatterns = [

    path('registration/',views.registration, 
         name='signup'),

    path('login/', LoginView.as_view(
        template_name = 'users/login.html'), 
        name='login'
        ),
    
    path('logout/', LogoutView.as_view(
        template_name = 'users/logout.html'),
        name='logout'),

    path('profile/<int:pk>/', views.ProfileView.as_view(), 
         name='profile'),



]

devforum-1.0/templates/footer.html
<footer>
    
</footer>

devforum-1.0/templates/index.html
{% extends 'wrapper.html' %}
{% block title %}
<title>HomePage-Forum</title>
{% endblock title %}
{% block content %}
 <style>
  .card{
    width: 100%;
    margin-top: 2%;
  }
 </style>
   {% for object in object_list %}     
<div class="card">
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-right">
            <h4>
              <a href="{% url 'forum:problem_detail' object.id %}">{{object.title}}</a>
            </h4>
            <span>{{ object.body.html|safe|truncatewords:"15" }}</span>
          </div>
        </div>
        <div class="data">
          <span class="badge rounded-pill text-bg-success">
            <i class="fas fa-user"></i>
            {{object.author}}
          </span>
          <span class="badge rounded-pill text-bg-primary">
            <i class="fas fa-eye"></i>
            {{object.views}}
          </span>
          <span class="badge rounded-pill text-bg-primary">
            <i class="fas fa-thumbs-up"></i>
            {{object.like}}
          </span>
          <span class="badge rounded-pill text-bg-primary">
            <i class="fas fa-thumbs-down"></i>
            {{object.dislike}}
          </span>
          <div>
            {% for tag in object.tags.all %}
            <span class="badge rounded-pill text-bg-warning">
              <i class="{{tag.icon}}"></i>
              {{tag}}
            </span>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>              
  {% endfor %}
                      
{% endblock content %}

devforum-1.0/templates/navbar.html
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bold" href="/">Devforum</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                  {% if request.user.is_authenticated %}
                  <a href="{% url 'users:profile' request.user.id %}" class="btn btn-primary">{{ request.user.username }}</a>
                  <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                  {% else %}
                  <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                  <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                  {% endif %}
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
</header>

devforum-1.0/templates/wrapper.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Fontawsome Api -- all icons come from there-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <!-- Bootstrap api -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
          crossorigin="anonymous">

    {% block title %} {% endblock title %}
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        <div class="container">
            {% block content %} {% endblock content %}
        </div>
    </main>

    {% include 'footer.html' %}

    <!-- Bootstrap popper js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" 
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" 
        crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" 
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" 
        crossorigin="anonymous">
    </script>
</body>
</html>