devforum-1.0/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls', namespace='forum')),
    path('users/', include('users.urls', namespace='users')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name = 'users/reset_password.html'), 
        name ='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'), 
        name ='password_reset_done'),
    path('reset/password/<str:uidb64>/<str:token>', auth_views.PasswordResetConfirmView.as_view(
         template_name = 'users/password_reset_confirm.html'),
         name ='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'users/password_reset_complete.html'),
        name ='password_reset_complete'),
    path("__debug__/", include("debug_toolbar.urls")),
]

devforum-1.0/forum/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'forum'
urlpatterns = [
    path('', cache_page(60*15)(views.HomePage.as_view()), name='home'),
    path('detail/<pk>', views.ProblemDetail.as_view(),name='problem_detail'),
    path('problem_add/', views.AddProblem.as_view(), name='add'),
]

devforum-1.0/users/urls.py
from django.urls import path, re_path

from django.contrib.auth.views import ( 
    LoginView,
    LogoutView,
    )   
from . import views

app_name = 'users'
urlpatterns = [

    path('registration/',views.registration, 
         name='signup'),

    path('login/', LoginView.as_view(
        template_name = 'users/login.html'), 
        name='login'
        ),
    
    path('logout/', LogoutView.as_view(
        template_name = 'users/logout.html'),
        name='logout'),

    path('profile/<int:pk>/', views.ProfileView.as_view(), 
         name='profile'),



]

devforum-1.0/users/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.core.signing import TimestampSigner
from django_resized import ResizedImageField
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
# from forum.models import Tag



class RegionChoices(models.TextChoices):
    andijon = "andijon", _("Andijon viloyati")
    buxoro = "buxoro", _("Buxoro viloyati")
    jizzax = "jizzax", _("Jizzax viloyati")
    qashqadaryo = "qashqadaryo", _("Qashqadaryo viloyati")
    navoiy = "navoiy", _("Navoiy viloyati")
    namangan = "namangan", _("Namangan viloyati")
    samarqand = "samarqand", _("Samarqand viloyati")
    suxondaryo = "suxondaryo", _("Suxondaryo viloyati")
    sirdaryo = "sirdaryo", _("Sirdaryo viloyati")
    toshkent = "toshkent", _("Toshkent viloyati")
    fargona = "fargona", _("Farg'ona viloyati")
    xorazm = "xorazm", _("Xorazm viloyati")
    qoraqalpoq = "qoraqalpoq", _("Qoraqalpog`iston Respublikasi")



class SpecChoices(models.TextChoices):
    fullstack = "FullStack dasturchi", _("FullStack dasturchi")
    frontend = "Front-End dasturchi", _("Front-End dasturchi")
    backend = "Back-End dasturchi", _("Back-End dasturchi")
    mobile = "Mobile dasturchi", _("Mobile dasturchi")
    uxui = "UX/UI dizayner", _("UX/UI dizayner")
    graphic = "Grafik dizayner", _("Grafik dizayner")
    qa = "QA muhandis", _("QA muhandis")
    gamedev = "O'yin dasturchisi", _("O'yin dasturchisi")
    tester = "Tester", _("Tester")
    hr = "HR menejer", _("HR menejer")
    pm = "Proyekt menejer", _("Proyekt menejer")
    lead = "Team Lead", _("Team Lead")
    seo = "SEO mutaxasis", _("SEO mutaxasis")
    other = "Boshqa soha", _("Boshqa soha")




class User(AbstractUser):
    bio = models.TextField(_("bio"), blank=True)
    avatar = ResizedImageField(
        size=[500, 500],
        crop=["middle", "center"],
        verbose_name=_("avatar"),
        quality=90,
        upload_to="user/%Y/%m",
        null=True,
        blank=True
    )
    region = models.CharField(
        _("region"),
        max_length=256,
        choices=RegionChoices.choices,
        blank=True
    )
    spec = models.CharField(
        _("specialization"),
        max_length=256,
        choices=SpecChoices.choices,
        blank=True
    )
    # technology = models.ManyToManyField(Ta related_name='user_technologies', blank=True)
    true_solutions = models.PositiveIntegerField(_("true solutions"), default=0)
    question_count = models.PositiveIntegerField(_("question"), default=0)
    answers_count = models.PositiveIntegerField(_("answers"), default=0)
    
    facebook = models.CharField(_("facebook"), max_length=256, blank=True)
    instagram = models.CharField(_("instagram"), max_length=256, blank=True)
    telegram = models.CharField(_("telegram"), max_length=256, blank=True)
    linkedin = models.CharField(_("linkedin"), max_length=256, blank=True)
    github = models.CharField(_("github"), max_length=256, blank=True)


    followers = models.ManyToManyField('self', symmetrical=False, blank=True)

    def count_followers(self):
        return self.followers.count()
    
    def count_following(self):
        return User.objects.filter(followers=self).count()

    created_at = models.DateTimeField(
        _("date created"),
        auto_now_add=True,
        null=True,
    )
    updated_at = models.DateTimeField(_("date updated"), auto_now=True)



    signer = TimestampSigner(sep=":")

    @property
    def avatar_url(self):
        return f"{settings.HOST}{self.avatar.url}" if self.avatar else ""
    
    def get_full_name(self):
        if self.first_name and self.last_name:
            return str(self.first_name + " " + self.last_name)
        else:
            return "To'ldirilmagan"
        
        
    
    
    def check_any_social_link(self):
        return any([
            self.facebook,
            self.instagram,
            self.telegram,
            self.linkedin,
            self.github,])
    

    
    def __str__(self):
        return f"{self.username}"

    class Meta:
        db_table = "user"
        swappable = "AUTH_USER_MODEL"
        verbose_name = _("user")
        verbose_name_plural = _("users")


def user_updated(sender,instance, created,  **kwargs):
    print('User Created')

post_save.connect(user_updated, sender=User)

devforum-1.0/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import ReCaptchaField
from .models import User


class RegisterForm(UserCreationForm):
    captcha = ReCaptchaField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})

class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)

devforum-1.0/users/views.py
import requests

from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView
from .models import User
from .forms import RegisterForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib import messages
from django.conf import settings

def registration(request):
    template_name = 'users/register.html'
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.add_message(request, messages.SUCCESS, f"Welcome { user.username } !!!")
            login(request,user)
            return redirect(f"/users/profile/{ user.id }/")
        else:
            messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    
    return render(request, template_name, {'form':form})


class ProfileView(DetailView):
    model = User
    template_name = 'users/profile.html'

devforum-1.0/templates/users/login.html
{% extends 'wrapper.html' %}
{% block title %}
<title>Login</title>
{% endblock title %}
{% block content %}
     <div class="form">
        <div class="row d-flex justify-content-center align-items-center h-100 mt-5">
            <div class="col-lg-12 col-xl-12">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form  class="mx-1 mx-md-4" method="POST">
                            {% csrf_token %}

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.username }}
                            <label class="form-label" for="form3Example1c">Your Name</label>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.password }}
                            <label class="form-label" for="form3Example3c">Your Password</label>
                          </div>
                        </div>

                       

                        <div class="form-check d-flex justify-content-center mb-5">
                          <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                          <label class="form-check-label" for="form2Example3">
                            I agree all statements in <a href="#!">Terms of service</a>
                          </label>
                        </div>
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Login</button>
                        </div>
      
                      </form>
      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
     </div>
{% endblock content %}

devforum-1.0/templates/users/logout.html
{% extends 'wrapper.html' %}
{% block title %}
<title>Log-out</title>
{% endblock title %}
{% block content %}
   <h2 class="m-auto text-center my-5 ">
        You logged out !!!
        Back to <a href="{% url 'forum:home'%}">home</a>
   </h2>
{% endblock content %}

devforum-1.0/templates/users/password_reset_complete.html
{% extends 'wrapper.html' %}
{% block title %}
<title> Password reset </title>
{% endblock title %}
{% block content %}
<div class="text-center" style="width: 80%; margin: 0 auto">
    <h1>Password reset complete</h1>
    <h6 style="width: 60%; margin: 0 auto">
      Your Password has been set. You may go ahead and login
    </h6>
  </div>
  <br />
  <div class="text-center">
    <a href="{% url 'users:login' %}">Login</a>
  </div>
  {% endblock content %}

devforum-1.0/templates/users/password_reset_confirm.html
{% extends 'wrapper.html' %}
{% block title %}
<title>Confirm Password </title>
{% endblock title %}
{% block content %}
     <div class="form">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
     </div>
     <script>
        document.getElementById('id_email').classList.add('form-control')
     </script>
{% endblock content %}

devforum-1.0/templates/users/password_reset_done.html
{% extends 'wrapper.html' %}
{% block title %}
<title> Sent </title>
{% endblock title %}
{% block content %}
<div class="text-center" style="width: 80%; margin: 0 auto">
    <h1 style="margin-top: 20px;">Password reset sent</h1> 
    <h5>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</h5><br>
    <h6 style="width: 60%; margin: 0 auto">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h6>
 </div>
 <div class="text-center">
   <a href="{% url 'forum:home' %}">Return to home page</a>
 </div>
{% endblock content %}

devforum-1.0/templates/users/profile.html
{% extends 'wrapper.html' %}
{% block title %}
<title>{{ request.user.username }}'s - Profile</title>
{% endblock title %}
{% block content %}
     <div class="d-flex justify-content-between align-items-center">
          <h1 class="mt-4">Profile</h1>
          <div><a href="{% url 'reset_password' %}" class="btn btn-outline-success">Password reset</a>
            <a href="{% url 'forum:add' %}" class="btn btn-outline-success">Ask something</a></div>
     </div>
        <section>
              <div class="row py-2">
                <div class="col-lg-4">
                  <div class="card mb-4">
                    <div class="card-body text-center">
                        {% if not user.avatar %}
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                        class="rounded-circle img-fluid" style="width: 150px;">
                        {% else %}
                        <img src="{{user.avatar_url}}" alt="avatar"
                        class="rounded-circle img-fluid" style="width: 150px;">
                        {% endif %}
                      <h5 class="my-3">{{ object.get_full_name }}</h5>
                      <p class="text-muted mb-1">{{user.spec}}</p>
                      <p class="text-muted mb-4">{{user.region}}</p>
                      <div class="d-flex justify-content-center mb-2">
                        <button type="button" class="btn btn-primary">Follow</button>
                        <button type="button" class="btn btn-outline-success ms-1">Edit</button>
                      </div>
                    </div>
                  </div>
                  <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                      <ul class="list-group list-group-flush rounded-3">
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                          <i class="fas fa-globe fa-lg text-warning"></i>
                          <p class="mb-0 text-primary mr-4"></p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                          <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                          <p class="mb-0">{{ user.github }}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                          <i class="fab fa-telegram fa-lg" style="color: #55acee;"></i>
                          <p class="mb-0">{{ user.telegram }}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                          <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                          <p class="mb-0">{{ user.instagram }}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                          <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                          <p class="mb-0">{{ user.facebook}}</p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-8">
                  <div class="card mb-4">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Full Name</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">{{ user.get_full_name }}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Email</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">{{ user.email }}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Username</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">{{user.username}}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Biography</p>
                        </div>
                        <div class="col-sm-9">
                          <p class="text-muted mb-0">{{user.bio}}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <p class="mb-0">Stack technologies</p>
                        </div>
                        <div class="col-sm-9">
                          {% for tech in user.technology.all %}
                            <span class="badge text-bg-primary m-0">
                                <i class="{{tech.icon}}"></i>
                                {{tech.title}}
                            </span>
                            {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                          <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                          </p>
                          <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                          <div class="progress rounded mb-2" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                          <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                          </p>
                          <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                          <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                          <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                          <div class="progress rounded mb-2" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                              aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        </section>
{% endblock content %}

devforum-1.0/templates/users/register.html
{% extends 'wrapper.html' %}
{% block title %}
<title>User - SigUp</title>
{% endblock title %}
{% block content %}
     <div class="form">
        <div class="row d-flex justify-content-center align-items-center h-100 mt-5">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form  class="mx-1 mx-md-4" method="POST">
                            {% csrf_token %}
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.username }}
                            <label class="form-label" for="form3Example1c">Your Name</label>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.email }}
                            <label class="form-label" for="form3Example3c">Your Email</label>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.password1 }}
                            <label class="form-label" for="form3Example4c">Password</label>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.password2 }}
                            <label class="form-label" for="form3Example4cd">Repeat your password</label>
                          </div>
                        </div>
      
                        <div class="form-check d-flex justify-content-center align-items-center flex-column mb-5">
                         <p> {{ form.captcha }}</p><br>
                          {% if form.captcha.errors %}
                            {% for i in form.captcha.errors %}
                              <p>{{ i }}</p>
                            {% endfor %}
                          {% endif %}
                        </div>
                        
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Register</button>
                        </div>
      
                      </form>
      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
     </div>
{% endblock content %}

devforum-1.0/templates/users/reset_password.html
{% extends 'wrapper.html' %}
{% block title %}
<title>Password Reset</title>
{% endblock title %}
{% block content %}
     <div class="form">
      <div class="form">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
     </div>
     </div>
     <script>
        document.getElementById('id_email').classList.add('form-control')
     </script>
{% endblock content %}