billur_crm/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('statistics/', include('main.urls', namespace='main')),
    path('calculations/', include('statistic.urls',namespace='statistic')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billur_crm/main/urls.py
from django.urls import path
from .views import OrdersView,OrderDetail, OrdersStatusView, StorageView, ExpensesView, StaffsView


app_name = 'main'
urlpatterns = [
    path('orders/', OrdersView.as_view(), name='order_page'),
    path('orders/orders_status', OrdersStatusView.as_view(), name='orders_status'),
    path('orders/<pk>', OrderDetail.as_view(), name='order_detail'),
    path('storage/', StorageView.as_view(), name='storage'),
    path('expenses/',ExpensesView.as_view(), name='expenses'),
    path('staffs/',StaffsView.as_view(), name='staffs'),
]

billur_crm/products/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'products'
urlpatterns = [
    path('', views.ProductsList.as_view(), name='product_list'),
    path('products/<pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('product/add_to_card/<product_id>', views.add_to_cart, name='add_to_card'),
    path('orders/', views.CustomerOrdersView.as_view(), name='customer_order_page'),
    path('orders/<pk>', views.CustomerOrderDetail.as_view(), name='cutomer_order_detail'),
    path('cart_page/', views.CardView.as_view(), name='cart'),
    path('wishlist/toggle/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.WishListView.as_view(),name='wishlist'),
    path('logout', LogoutView.as_view(), name='logout'),
]

billur_crm/products/models.py
from django.db import models
from django_resized import ResizedImageField


class Storage(models.Model):
    name = models.CharField(max_length=250)
    last_updated = models.DateTimeField(auto_now_add=True)
    

    def overall_products_number(self):
        count = 0
        for i in self.products.all():
            count += i.amount
        return count
    


    def __str__(self):
        return self.name

class ProductCategory(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)


    def __str__(self):
        return str(self.name)


class ProductTag(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)


    def __str__(self):
        return str(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.IntegerField(default=0)
    old_price = models.IntegerField(default=0)
    amount = models.IntegerField(default=0)
    discount = models.PositiveIntegerField(default=0)
    image = ResizedImageField(size=[570,650],upload_to='movie_posters/')
    description = models.TextField(blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')
    tag = models.ForeignKey(ProductTag, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    storage = models.ForeignKey(Storage, on_delete=models.CASCADE, related_name='products', blank=True, null=True)


    class Meta:
        ordering = ['id']


    def products_status_in_storage(self):
        overall_products = self.storage.overall_products_number()
        if overall_products > 0:
            percentage = (self.amount / overall_products) * 100
            return round(percentage, 2)
        else:
            return 0


    def __str__(self):
        return str(self.name)
    

billur_crm/products/forms.py
from django import forms
from .models import Product

class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['tag']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'price':forms.NumberInput(attrs={'class':'form-control'}),
            'old_price':forms.NumberInput(attrs={'class':'form-control'}),
            'amount':forms.NumberInput(attrs={'class':'form-control'}),
            'discount':forms.NumberInput(attrs={'class':'form-control'}),
            'image':forms.FileInput(attrs={'class':'form-control-file'}),
            'description':forms.TextInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'storage':forms.Select(attrs={'class':'form-control'}),

            # 'tag':forms.Select(attrs={'class':'form-control'}),
        }

billur_crm/products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView
from .models import Product, ProductCategory, ProductTag
from django.http import HttpResponse
from main.models import Orders, CartItems, OrderItems, WishList
from django.views import View
from .forms import ProductAddForm
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login , authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

class ProductsList(FormView,ListView):
    model = Product
    form_class = ProductAddForm
    template_name = 'products/ecom-product-grid.html'
    paginate_by = 8
    success_url = reverse_lazy('/')

    
    def get_queryset(self):
        queryset = super().get_queryset()
        if 'billur_products' in self.request.GET:
            queryset = queryset.filter(category__name='Billur')
        elif 'extra-products' in self.request.GET:
            queryset = queryset.filter(category__name='Boshqalar')
        elif 'search' in self.request.GET:
            queryset = queryset.filter(name__icontains=self.request.GET.get('product'))
        return queryset



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        wishlist = WishList.objects.get_or_create(session_key=self.request.session.session_key),
        try:
            user = User.objects.get(id=self.request.user.id)
        except User.DoesNotExist:
            user = None
        # print(user)
        context.update({
            'categories': ProductCategory.objects.all(),
            'tags': ProductTag.objects.all(),
            'wishlist_products':wishlist,
            'login_form': AuthenticationForm(),
            'product_form': ProductAddForm(),
            'user': user,
        })  
        return context
    

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        if 'new_product_add' in request.POST:
            form = ProductAddForm(request.POST,request.FILES)
            if form.is_valid():
                try:
                    product = Product.objects.get(name=form.cleaned_data['name'])
                    product.name = form.cleaned_data['name']
                    product.amount = form.cleaned_data['amount']
                    product.discount = form.cleaned_data['discount']
                    product.price = form.cleaned_data['price']
                    product.image = form.cleaned_data['image']
                    product.description = form.cleaned_data['description']
                    product.category = form.cleaned_data['category']
                    product.save()
                except Product.DoesNotExist:
                    form.save()
            else:
                print(form.errors)
                print('form is not valid -----------------')
            # return self.form_invalid(form)
        if 'login' in request.POST:
            login_form = AuthenticationForm(data=request.POST)
            if login_form.is_valid():
                user = authenticate(
                    username=login_form.cleaned_data['username'],
                    password=login_form.cleaned_data['password'],
                )
                if user is not None:
                    login(request, user)
                    print('logged in')
                    return redirect('products:product_list')
                else:
                    print('wrong')
                    return redirect('products:product_list')
                
        return render(request, self.template_name, self.get_context_data())

    
class ProductDetail(DetailView):
    model = Product
    template_name = 'products/ecom-product-detail.html'


def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    session_key = request.session.session_key
    if 'quantity' in request.POST:
        quantity = request.POST.get('quantity')
    

    if not session_key:
        request.session.save()
        session_key = request.session.session_key

    
    try:
        cart_item = CartItems.objects.get(session_key=session_key, product_id=product.id)
        quantity = request.POST.get('quantity')
        if quantity != None:
            if product.amount == 0 or product.amount < int(quantity):
                return HttpResponse('<h1>Omborda Mahsulot yetrali emas</h1>')

            cart_item.quantity += int(quantity)
            cart_item.save()


    except CartItems.DoesNotExist:
        quantity = request.POST.get('quantity')
        if quantity:
            quantity = int(quantity)
            CartItems.objects.create(
                product_id=product_id,
                session_key=session_key,
            )
            cart_item = CartItems.objects.get(session_key=session_key, product_id = product_id)
            cart_item.quantity += quantity
            cart_item.save()
        else:
            cart_item = CartItems.objects.create(
                product_id=product_id,
                session_key=session_key,
            )
            cart_item.quantity += 1
            cart_item.save()
    return redirect('products:product_list')


class CardView(View):
    template_name ='card_page.html'

    def get_context_data(self, request,**kwargs):
        session_key = request.session.session_key
        try:
            cart_items = CartItems.objects.filter(session_key=session_key)
        except CartItems.DoesNotExist:
            return HttpResponse('<h1>Savatcha Mahsuotlari topilmadi!!! oldin Savatchaga mahsulot qo\'shing</h1>')
        kwargs['cart_items'] = cart_items
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data(request))


    def post(self, request, *args, **kwargs):
        ctxt = {}

        if 'add_quantity' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product'))
            quantity = request.POST.get('quantity')
            product.quantity = int(quantity)
            product.save()

        elif 'delete' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product_delete'))
            product.delete()
        elif 'order' in request.POST:
            session_key = request.session.session_key
            cart_items = CartItems.objects.filter(session_key=session_key)
            order_amount = sum([i.overall_price() for i in cart_items])
            # print(cart_items)
            if order_amount > 100000:
                order_instance = Orders.objects.create(
                customer_full_name=request.POST.get('customer_full_name'),
                address=request.POST.get('address'),
                target=request.POST.get('target'),
                phone_number=request.POST.get('phone_number'),
                session_key=session_key,
                )
                print(cart_items)
                for i in cart_items:
                    print(i.product)
                    order_items = OrderItems.objects.create(
                        quantity = i.quantity,
                        sessionkey = session_key,
                        order = order_instance,
                        products = i.product
                        )
                    # print()
                cart_items.delete()
                # order_instance.items.set(cart_items)
            else:
                print(sum([i.overall_price() for i in cart_items]))
                return HttpResponse("<h1>Umumiy qiymat 100000 so'mni tashkil etganda buyurtma berish mumkin!!!</h1>")
            

        return render(request, self.template_name, self.get_context_data(request,**ctxt))


class CustomerOrdersView(View):
    template_name = 'customers/customer_orders.html'


    def get_context_data(self, *args, **kwargs):
        return kwargs
    

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        session_key = request.session.session_key
        context['orders'] = Orders.objects.filter(session_key=session_key)
        return render(request, self.template_name, context)
    

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template_name, self.get_context_data(**context))


class CustomerOrderDetail(DetailView):
    model = Orders
    template_name = 'order_detail.html'


class WishListView(View):
    template_name = 'wishlist.html'
    

    def get_context_data(self, **kwargs):
        session_key = self.request.session.session_key
        print(self.request.session.session_key)
        wishlist = WishList.objects.get(session_key=session_key)
        products = wishlist.products.all()
        status = False
        if products:
            status = True
        else:
            pass
        kwargs['wishlist'] = wishlist
        kwargs['wishlist_status'] = status
        return kwargs


    def get(self,reqeust, *args, **kwargs):
        return render(reqeust, self.template_name, self.get_context_data())
    

    def post(self,request, *args, **kwargs):
        ctxt = {}
        if 'add_to_card' in request.POST:
            request = request
            product_id = request.POST.get('product')
            print(product_id)
            add_to_cart(request,product_id)
        elif 'delete' in request.POST:
            wishlist = WishList.objects.get(session_key=request.session.session_key)
            product_id = request.POST.get('product_delete')
            print(product_id)

billur_crm/templates/products/ecom-product-detail.html
{% extends 'wrapper.html' %}
{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="vendor/star-rating/star-rating-svg.css">{% endblock style %}
{% block title %}{{ object.name }}{% endblock title %}
{% block content %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-xl-3 col-lg-6  col-md-6 col-xxl-5 ">
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade show active" id="first" style="width: 100%;">
                                                <img class="img-fluid" src="{{ object.image.url }}" alt="" style="width: 100%;">
                                            </div>
                                        </div>
                                        <div class="tab-slide-content new-arrival-product mb-4 mb-xl-0">
                                            <!-- Nav tabs -->
                                            <ul class="nav slide-item-list mt-3" role="tablist">
                                                <li role="presentation" class="show">
                                                    <a href="#first" role="tab" data-toggle="tab">
                                                        <img class="img-fluid" src="images/tab/1.jpg" alt="" width="50">
                                                    </a>
                                                </li>
                                                <li role="presentation">
                                                    <a href="#second" role="tab" data-toggle="tab"><img class="img-fluid" src="images/tab/2.jpg" alt="" width="50"></a>
                                                </li>
                                                <li role="presentation">
                                                    <a href="#third" role="tab" data-toggle="tab"><img class="img-fluid" src="images/tab/3.jpg" alt="" width="50"></a>
                                                </li>
												<li role="presentation">
                                                    <a href="#for" role="tab" data-toggle="tab"><img class="img-fluid" src="images/tab/4.jpg" alt="" width="50"></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <!--Tab slider End-->
                                    <div class="col-xl-9 col-lg-6  col-md-6 col-xxl-7 col-sm-12">
                                        <div class="product-detail-content">
                                            <!--Product details-->
                                            <div class="new-arrival-content pr">
                                                <h4>{{ object.name }}</h4>
												<div class="d-table mb-2">
													<p class="price float-left d-block">Narxi: {{ object.price }} so'm</p>
                                                </div>
                                                <p>Omborda:<span class="item"> {{ object.amount }}ta <i class="fa fa-shopping-basket"></i></span></p>
                                                <p>Brand: <span class="item">{{ object.category.name }}</span></p>
                                                <p>Chegirma: {{ object.discount }}%</p>
                                                <p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
                                                    If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>
                                                <!--Quantity start-->
											<form action="{% url 'products:add_to_card' object.id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="col-2 px-0">
													<input type="number" name="quantity" class="form-control input-btn input-number" value="1">
												</div>
                                                <!--Quanatity End-->
                                                <div class="shopping-cart mt-3">
                                                    <button class="btn btn-primary btn-lg" type="submit"><i
                                                            class="fa fa-shopping-basket mr-2"></i>Add
                                                        to cart
                                                    </button>
                                                </div>
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
					<!-- review -->
					<div class="modal fade" id="reviewModal">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">Review</h5>
									<button type="button" class="close" data-dismiss="modal"><span>&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<form>
										<div class="text-center mb-4">
											<img class="img-fluid rounded" width="78" src="./images/avatar/1.jpg" alt="DexignZone">
										</div>
										<div class="form-group">
											<div class="rating-widget mb-4 text-center">
												<!-- Rating Stars Box -->
												<div class="rating-stars">
													<ul id="stars">
														<li class="star" title="Poor" data-value="1">
															<i class="fa fa-star fa-fw"></i>
														</li>
														<li class="star" title="Fair" data-value="2">
															<i class="fa fa-star fa-fw"></i>
														</li>
														<li class="star" title="Good" data-value="3">
															<i class="fa fa-star fa-fw"></i>
														</li>
														<li class="star" title="Excellent" data-value="4">
															<i class="fa fa-star fa-fw"></i>
														</li>
														<li class="star" title="WOW!!!" data-value="5">
															<i class="fa fa-star fa-fw"></i>
														</li>
													</ul>
												</div>
											</div>
										</div>
										<div class="form-group">
											<textarea class="form-control" placeholder="Comment" rows="5"></textarea>
										</div>
										<button class="btn btn-success btn-block">RATE</button>
									</form>
								</div>
							</div>
						</div>
					</div>
                </div>
{% endblock content %}
{% block scripts %}
	<script src="./vendor/star-rating/jquery.star-rating-svg.js"></script>
{% endblock scripts%}

billur_crm/templates/products/ecom-product-grid.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Products{% endblock title %}
{% block style %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<script>
    $(document).ready(function () {
        $('.wishlist-toggle').click(function () {
            var productId = $(this).data('product-id');

            $.ajax({
                url: '/wishlist/toggle/' + productId + '/',
                type: 'POST',
                dataType: 'json',
                headers: { 'X-CSRFToken': getCookie('csrftoken') }, // Include CSRF token
                success: function (data) {
                    var wishlistToggle = $('.wishlist-toggle[data-product-id="' + productId + '"]');
					var heartIcon = wishlistToggle.find('#wishlist-icon');
                    if (data.is_added) {
                        // wishlistToggle.css('color', 'red');
						heartIcon.addClass('in_wishlist')
						console.log(heartIcon);
                    } else {
                        // wishlistToggle.css('color', 'blue');
						heartIcon.removeClass('in_wishlist')

                    }
                }
            });
        });

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    });
</script>
<style>
	.icon{
		color: blue;
	}
	.in_wishlist{
		color: red;
	}
</style>
{% endblock style %}
{% block content %}
{% load crispy_forms_tags %}
                <div class="page-titles" >
						<div class="d-flex justify-content-between align-items-center flex-wrap">
							<div>
								<form action="" method="GET" class="d-flex flex-wrap">
									{% csrf_token %}
									<button type="submit" class="btn btn-outline-success mx-2 my-2" name="billur_products">Billur mahsulotlari</button>
									<button type="submit" class="btn btn-outline-success mx-2 my-2" name="extra-products">Qo'shimcha mahsulotlar</button>
								</form>
							</div>
							{% if user.is_staff %}
							<div>
								<button type="button" class="btn btn-outline-secondary mt-2" name="new_product_add" data-toggle="modal" data-target="#exampleModal">Mahsuot qo'shish</button>
							</div>
							{% else %}
							<div>
								<button type="button"  data-target="#loginModal" data-toggle="modal" class="btn btn-outline-success">Log in</button>
							</div>
							{% endif %}
						</div>
                </div>
                <div class="row">
					{% for i in object_list %}
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="new-arrival-product">
									<a href="{% url 'products:product_detail' i.id %}">
                                    <div class="new-arrivals-img-contnent" style="width: 100%;height: 300px;">
                                        <img class="img-fluid" src="{{ i.image.url }}" alt="" style="width: 100%;height:100%;">
                                    </div>
                                    <div class="new-arrival-content mt-3">
                                        <div>
											<div class="d-flex justify-content-between align-items-center pr-3">
												<h4>
													<a>{{ i.name }}</a>
													<span class="text-danger">{% if i.category.name == 'Billur' %}( Billur ){% else %}{% endif %}</span>
												</h4>
												<p class="px-2 py-2 wishlist-toggle"   style="cursor: pointer;" data-product-id="{{ i.id }}" name="wishlist">
													<i id="wishlist-icon" class="fas fa-heart icon {% if i in wishlist_products.products.all %}in_wishlist{% endif %}" style="font-size: 20px;"></i>
												</p>
											</div>
											<p>Omborda : {{ i.amount }}ta</p>
										</div>
										{% if i.old_price > 0 %}
										<div class="badge badge-light text-danger"><strike>{{ i.old_price }} so'm</strike></div>
										{% endif %}
                                        <div class="mt-2" 
											style="font-weight: 600;
												color: #0B2A97;
												font-size: 24px;
												">
												{{ i.price }}so'm
										</div>
                                    </div>
									</a>
                                </div>
                            </div>
                        </div>
                    </div>
					{% endfor %}
                </div>
            </div>
			<div class='d-flex justify-content-center align-items-center'>
				<nav>
					<ul class="pagination pagination-gutter">
						{% if current_page.has_previous %}
						<li class="page-item page-indicator">
							<a class="page-link" href="?page=1">
								<i class="la la-angle-left"></i>
							</a>
						</li>
						{% endif %}
						{% for page_number in paginator.page_range %}
						<li class="page-item {% if page_number == current_page.number %} active {% endif %}">
							<a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
						</li>
						{% endfor %}
						{% if current_page.has_next %}
						<li class="page-item page-indicator">
							<a class="page-link" href="?page={{ paginator.num_pages }}">
								<i class="la la-angle-right"></i></a>
						</li>
						{% endif %}
					</ul>
				</nav>
			</div>
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
				  <div class="modal-content">
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
					<div class="modal-header">
					  <h5 class="modal-title" id="exampleModalLabel">Mahsulot Qo'shish</h5>
					  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					  </button>
					</div>
					<div class="modal-body">
						
					{{ product_form }}
						
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
					  <button type="submit" class="btn btn-outline-secondary" name="new_product_add">Saqlash</button>
					</div>
				</form>
				  </div>
				</div>
			</div>
			<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
				<div class="modal-dialog" role="document">
				  <div class="modal-content">
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
					<div class="modal-header">
					  <h5 class="modal-title" id="exampleModalLabel">Mahsulot Qo'shish</h5>
					  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					  </button>
					</div>
					<div class="modal-body">
						
					{{ login_form|crispy }}
				
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
					  <button type="submit" class="btn btn-outline-secondary" name="login">Login</button>
					</div>
				</form>
				  </div>
				</div>
			</div>
{% endblock content %}
{% block scripts %}


{% endblock scripts %}